### ISSUE TITLE
app - only buffers on CC. never gets to PLAY state. cant debug receiver 

### ISSUE THREAD

**Issue by rowntreerob** [googlecast/CastVideos-chrome-material#1] opened 2015-05-06 17:05 UTC
followed instructions on readme, installed git project on linux system with chrome browser with chromecast plugin installed in browser. 

NOTE: unable to debug the reciever on *cc-IP:9222* due to "connection refused" 
   why is that? I thought the default receiver appId="4F8B3483" was supposed to be debuggable??

NOTE: the "cast_sender.js" is there , in the sender side debugger's listing of sources, but it has a DIFF prefix token value from what is listed in the console error on "cast_sender.js not found"

see attached sender log and screen shot of the browser showing that the app is "playing" on session on the local TV
![cc_polymer_2](https://cloud.githubusercontent.com/assets/169984/7498642/4d9e0e72-f3d7-11e4-9a54-c2a6e84173d9.png)
![cc_polymer_1](https://cloud.githubusercontent.com/assets/169984/7498647/53f282c6-f3d7-11e4-9cdc-698b0a429f56.png)

.

The TV goes to the BUFFERING state showing the image and has the yellow status bar animation at the bottom. It just stays in buffering state never getting to PLAY

**Comment by pengying** [comment] 2015-05-06 17:28
I think this is odd too but it follows the ux guidelines.  When a user connects to cast and the local media isn't playing, it should only load the media into cast.  To play the media, you'll need to hit the play button.

If local media is already playing then auto play content when connected to cast.

https://developers.google.com/cast/docs/design_checklist#cast-session-sequence 

The receiver app is debuggable.  Not sure why the connection is refused.  Have you registered your chromecast for debugging?

**Comment by rowntreerob** [comment] 2015-05-06 17:32
@pengying  thank you. my mistake on the UI ( extra clik on Play button is required )

So it plays fine!

footnote :   my device is registered.   appId="4F8B3483" is not currently debuggable.

**Comment by pengying** [comment] 2015-05-06 17:44
That's weird, I can get to the developer console.  Can you not even connect to select the remote debugging page?

I'm not quite sure what the cause could be :\.

**Comment by pengying** [comment] 2015-05-06 18:22
Is it cool if i close this out?

**Comment by rowntreerob** [comment] 2015-05-06 18:42
yes

**Comment by rowntreerob** [comment] 2015-05-06 18:48
https://plus.google.com/u/0/+CarlosSolorzanoInstantBits/posts/HxqZvFnKisZ

**Closed** 2015-05-06 18:47 UTC
